username: 
password: 
phone_number:
wait_for_user: false # or true if you want it to wait for you to fill out forms, linkedin keeps data and reuses in other forms, meaning the more you fill the more applications will go through

positions:
- Data Scientist
- # Another position you want to search for
- # A third position you want to search for

locations:
- Remote
- # A second location you want to search in 

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
